### ISSUE TITLE
Let private class fields go

### ISSUE THREAD

**Issue by kapouer** [marijnh/esmoduleserve#3]
I tried to PR this but i ended up doing a PR against my own repo.
Anywy it's there:
https://github.com/kapouer/esmoduleserve/pull/1

**Comment by kapouer** [comment]
https://github.com/kapouer/esmoduleserve/pull/1/commits/06c7ad725b0ddac4d5a02999c282e714ec607f44

**Comment by marijnh** [comment]
I'd be okay with an option to enable Acorn plugins, but I don't want to hard-code a specific set of them in the library.
